platform :ios, '8.0'

target 'ZHLBaseApp' do
  pod 'AFNetworking', '~> 3.1.0'
  pod 'SDWebImage','~> 3.8.1'
  pod 'MJExtension'
  pod 'Masonry'
  pod 'NullSafe'
  pod 'Reachability'
  pod 'SVProgressHUD','~> 0.9'
  pod 'KissXML', '~> 5.0'
  pod 'YYText'
  pod 'MJRefresh'
  pod 'DZNEmptyDataSet'
  pod 'BlocksKit'
  pod 'FMDB'
  pod 'MKNetworkKit', '~> 0.87'
end
